

name: Terraform CI/CD
on:  
  
  pull_request:
    branches: [ "main" ]
  push: 
    branches: 
      - main
  

jobs:

  terraform_scan:
    name: terraform_scan
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v7.0.0

      -  uses: hashicorp/setup-terraform@v2.0.3
  

 
   
      - uses: actions/checkout@v4

     
      - name: Run a one-line script
        run: echo Hello, world!

  
      - name: Run a multi-line script
        run: "hello sujit bhai!"

        
         
